module.exports = {
  errorSchema: require('./errorSchema'),
  managersSchema: require('./managersSchema'),
  metaSchema: require('./metaSchema'),
  playerAlbumSchema: require('./playerAlbumSchema'),
  playerSchema: require('./playerSchema'),
  playersSchema: require('./playersSchema'),
  playerStatsSchema: require('./playerStatsSchema'),
  rootSchema: require('./rootSchema'),
  seasonHatTricksSchema: require('./seasonHatTricksSchema'),
  seasonSchema: require('./seasonSchema'),
  seasonsSchema: require('./seasonsSchema'),
  seasonTableSchema: require('./seasonTableSchema'),
  seasonTopAssistsSchema: require('./seasonTopAssistsSchema'),
  seasonTopCleanSheetsSchema: require('./seasonTopCleanSheetsSchema'),
  seasonTopScorersSchema: require('./seasonTopScorersSchema'),
  teamSchema: require('./teamSchema'),
  teamSquadSchema: require('./teamSquadSchema'),
  teamSquadsSchema: require('./teamSquadsSchema'),
  teamsSchema: require('./teamsSchema'),
  teamStatsSchema: require('./teamStatsSchema'),
}
