module.exports = {
  playersRoute: require('./playersRoute'),
  playerRoute: require('./playerRoute'),
  playerAlbumRoute: require('./playerAlbumRoute'),
  playerStatsRoute: require('./playerStatsRoute'),
  seasonsRoute: require('./seasonsRoute'),
  seasonRoute: require('./seasonRoute'),
  seasonHatTricksRoute: require('./seasonHatTricksRoute'),
  seasonTableRoute: require('./seasonTableRoute'),
  seasonTopAssistsRoute: require('./seasonTopAssistsRoute'),
  seasonTopScorersRoute: require('./seasonTopScorersRoute'),
  teamsRoute: require('./teamsRoute'),
  teamRoute: require('./teamRoute'),
  teamSquadsRoute: require('./teamSquadsRoute'),
  teamSquadRoute: require('./teamSquadRoute'),
  teamStatsRoute: require('./teamStatsRoute'),
}
