module.exports = {
  managersRoute: require('./managersRoute'),
  playersRoute: require('./playersRoute'),
  playerRoute: require('./playerRoute'),
  playerAlbumRoute: require('./playerAlbumRoute'),
  playerStatsRoute: require('./playerStatsRoute'),
  rootRoute: require('./rootRoute'),
  seasonsRoute: require('./seasonsRoute'),
  seasonRoute: require('./seasonRoute'),
  seasonHatTricksRoute: require('./seasonHatTricksRoute'),
  seasonTableRoute: require('./seasonTableRoute'),
  seasonTopAssistsRoute: require('./seasonTopAssistsRoute'),
  seasonTopCleanSheetsRoute: require('./seasonTopCleanSheetsRoute'),
  seasonTopScorersRoute: require('./seasonTopScorersRoute'),
  teamsRoute: require('./teamsRoute'),
  teamRoute: require('./teamRoute'),
  teamSquadsRoute: require('./teamSquadsRoute'),
  teamSquadRoute: require('./teamSquadRoute'),
  teamStatsRoute: require('./teamStatsRoute'),
}
